### ISSUE TITLE
cant get it to work in app

### ISSUE THREAD

**Issue by ashtonsmith** [emcniece/particle-angular-starter#5]
hi - I took this and tried to package for android with phonegap and also cordova on my PC, i cant get it to display anything other than "back" in the top left corner when running on my android device (but it works perfectly inbrowser on my PC) - any idea? - Thanks
![2015-07-22 01 31 45](https://cloud.githubusercontent.com/assets/7677767/8816444/3cc8dfa6-307b-11e5-9504-e66a87bdbbe8.png)

**Comment by emcniece** [comment]
Very interesting. I'd like to see the console logs from your phone! One way to do this is to enable developer mode while having your mobile device connected to your computer via USB, then visiting chrome://inspect - another way is to enable the Debugging option from within Phonegap and using their interface.

My current suspicion is that the Ionic assets aren't being loaded.

**Comment by emcniece** [comment]
If the asset reference is indeed the problem, this branch should solve it: https://github.com/emcniece/particle-angular-starter/tree/localize_ionic

Please feel free to download and test through your build process, or if you have modified the code already you can look at the very simple updates [over here](https://github.com/emcniece/particle-angular-starter/compare/localize_ionic?expand=1).

**Comment by ashtonsmith** [comment]
ahh - localized version works - thanks for that

**Comment by emcniece** [comment]
Merged to master! Thanks for the confirmation.
